Search.appendIndex(
    [
                {
            "fqsen": "\\Collecthor\\DataInterfaces\\BoundedVariableInterface",
            "name": "BoundedVariableInterface",
            "summary": "Models\u0020a\u0020variable\u0020that\u0020has\u0020known\u0020upper\u0020and\u0020lower\u0020bounds.",
            "url": "classes/Collecthor-DataInterfaces-BoundedVariableInterface.html"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\BoundedVariableInterface\u003A\u003AgetLowerBound\u0028\u0029",
            "name": "getLowerBound",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-BoundedVariableInterface.html#method_getLowerBound"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\BoundedVariableInterface\u003A\u003AgetUpperBound\u0028\u0029",
            "name": "getUpperBound",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-BoundedVariableInterface.html#method_getUpperBound"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\ClosedVariableInterface",
            "name": "ClosedVariableInterface",
            "summary": "A\u0020closed\u0020variable\u0020is\u0020a\u0020variable\u0020with\u0020a\u0020finite\u0020number\u0020of\u0020valid\u0020values",
            "url": "classes/Collecthor-DataInterfaces-ClosedVariableInterface.html"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\ClosedVariableInterface\u003A\u003AgetValueOptions\u0028\u0029",
            "name": "getValueOptions",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-ClosedVariableInterface.html#method_getValueOptions"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\InvalidValueInterface",
            "name": "InvalidValueInterface",
            "summary": "This\u0020models\u0020a\u0020value\u0020that\u0020is\u0020not\u0020valid\u0020according\u0020to\u0020the\u0020survey\u0020structure",
            "url": "classes/Collecthor-DataInterfaces-InvalidValueInterface.html"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\InvalidValueInterface\u003A\u003AgetRawValue\u0028\u0029",
            "name": "getRawValue",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-InvalidValueInterface.html#method_getRawValue"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\InvalidValueInterface\u003A\u003AisSystemMissing\u0028\u0029",
            "name": "isSystemMissing",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-InvalidValueInterface.html#method_isSystemMissing"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\JavascriptVariableInterface",
            "name": "JavascriptVariableInterface",
            "summary": "This\u0020interface\u0020extends\u0020the\u0020variable\u0020interface\u0020and\u0020adds\u0020methods\u0020for\u0020doing\u0020the\u0020annotation\u0020on\u0020the\u0020client\u0020side.",
            "url": "classes/Collecthor-DataInterfaces-JavascriptVariableInterface.html"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\JavascriptVariableInterface\u003A\u003AgetJavascriptRepresentation\u0028\u0029",
            "name": "getJavascriptRepresentation",
            "summary": "This\u0020creates\u0020a\u0020plain\u0020javascript\u0020object\u0020with\u0020the\u0020following\u0020structure\u003A\n\u007B\n\u0020\u0020\u0020\u0020getName\u0028\u0029\u003A\u0020string,\n\u0020\u0020\u0020\u0020getTitle\u0028string\u007Cnull\u0020locale\u0029\u003A\u0020string,\n\u0020\u0020\u0020\u0020getValue\u0028dict\u0020record\u0029\u003A\u0020TBD,\n\u0020\u0020\u0020\u0020getMeasure\u0028\u0029\u003A\u0020nominal\u007Cordinal\u007Cscale\n\u0020\u0020\u0020\u0020getDisplayValue\u0028dict\u0020record,\u0020string\u007Cnull\u0020locale\u0029\u003A\u0020string\n\u007D",
            "url": "classes/Collecthor-DataInterfaces-JavascriptVariableInterface.html#method_getJavascriptRepresentation"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\JavascriptVariableSetInterface",
            "name": "JavascriptVariableSetInterface",
            "summary": "A\u0020javascript\u0020variable\u0020set\u0020guarantees\u0020that\u0020all\u0020variables\u0020can\u0020expose\u0020an\u0020object\u0020for\u0020annotating\u0020responses\u0020on\u0020the\u0020client\nside",
            "url": "classes/Collecthor-DataInterfaces-JavascriptVariableSetInterface.html"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\JavascriptVariableSetInterface\u003A\u003AgetVariableNames\u0028\u0029",
            "name": "getVariableNames",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-JavascriptVariableSetInterface.html#method_getVariableNames"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\JavascriptVariableSetInterface\u003A\u003AgetVariable\u0028\u0029",
            "name": "getVariable",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-JavascriptVariableSetInterface.html#method_getVariable"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\JavascriptVariableSetInterface\u003A\u003AgetVariables\u0028\u0029",
            "name": "getVariables",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-JavascriptVariableSetInterface.html#method_getVariables"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\Measure",
            "name": "Measure",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-Measure.html"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\Measure\u003A\u003ANominal",
            "name": "Nominal",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\Measure\u003A\u003AOrdinal",
            "name": "Ordinal",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\Measure\u003A\u003AScale",
            "name": "Scale",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\MissingValueInterface",
            "name": "MissingValueInterface",
            "summary": "This\u0020models\u0020a\u0020missing\u0020value",
            "url": "classes/Collecthor-DataInterfaces-MissingValueInterface.html"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\MissingValueInterface\u003A\u003AisSystemMissing\u0028\u0029",
            "name": "isSystemMissing",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-MissingValueInterface.html#method_isSystemMissing"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\NumericValueInterface",
            "name": "NumericValueInterface",
            "summary": "A\u0020numeric\u0020value",
            "url": "classes/Collecthor-DataInterfaces-NumericValueInterface.html"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\NumericValueInterface\u003A\u003AgetRawValue\u0028\u0029",
            "name": "getRawValue",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-NumericValueInterface.html#method_getRawValue"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\NumericVariableInterface",
            "name": "NumericVariableInterface",
            "summary": "A\u0020variable\u0020for\u0020which\u0020all\u0020valid\u0020values\u0020are\u0020numeric\u0020values",
            "url": "classes/Collecthor-DataInterfaces-NumericVariableInterface.html"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\NumericVariableInterface\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "Extracts\u0020the\u0020variable\u0020value\u0020from\u0020a\u0020record",
            "url": "classes/Collecthor-DataInterfaces-NumericVariableInterface.html#method_getValue"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\NumericVariableInterface\u003A\u003AgetDisplayValue\u0028\u0029",
            "name": "getDisplayValue",
            "summary": "Extract\u0020a\u0020display\u0020value\u0020from\u0020a\u0020record\nIf\u0020a\u0020locale\u0020is\u0020given\u0020the\u0020display\u0020value\u0020should\u0020be\u0020returned\u0020using\u0020the\u0020given\u0020locale.\u0020If\u0020the\u0020locale\u0020is\u0020not\u0020available\na\u0020fallback\u0020MUST\u0020be\u0020used\u0020and\u0020an\u0020exeception\u0020MUST\u0020NOT\u0020be\u0020thrown",
            "url": "classes/Collecthor-DataInterfaces-NumericVariableInterface.html#method_getDisplayValue"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\RecordInterface",
            "name": "RecordInterface",
            "summary": "Models\u0020a\u0020record\u0020that\u0020internally\u0020stores\u0020its\u0020data\u0020in\u0020an\u0020associative\u0020array",
            "url": "classes/Collecthor-DataInterfaces-RecordInterface.html"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\RecordInterface\u003A\u003AgetDataValue\u0028\u0029",
            "name": "getDataValue",
            "summary": "Retrieve\u0020a\u0020value\u0020given\u0020by\u0020path\u0020to\u0020the\u0020data.",
            "url": "classes/Collecthor-DataInterfaces-RecordInterface.html#method_getDataValue"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\RecordInterface\u003A\u003AgetRecordId\u0028\u0029",
            "name": "getRecordId",
            "summary": "Return\u0020the\u0020unique\u0020ID\u0020of\u0020this\u0020record",
            "url": "classes/Collecthor-DataInterfaces-RecordInterface.html#method_getRecordId"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\RecordInterface\u003A\u003AgetStarted\u0028\u0029",
            "name": "getStarted",
            "summary": "Since\u0020there\u0020is\u0020no\u0020interface\u0020for\u0020immutable\u0020date\u0020times,\u0020implementations\u0020MUST\u0020return\u0020a\u0020fresh\u0020object\u0020every\u0020time.",
            "url": "classes/Collecthor-DataInterfaces-RecordInterface.html#method_getStarted"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\RecordInterface\u003A\u003AgetLastUpdate\u0028\u0029",
            "name": "getLastUpdate",
            "summary": "Since\u0020there\u0020is\u0020no\u0020interface\u0020for\u0020immutable\u0020date\u0020times,\u0020implementations\u0020MUST\u0020return\u0020a\u0020fresh\u0020object\u0020every\u0020time.",
            "url": "classes/Collecthor-DataInterfaces-RecordInterface.html#method_getLastUpdate"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\RecordInterface\u003A\u003AasArray\u0028\u0029",
            "name": "asArray",
            "summary": "Serialize\u0020the\u0020record\u0020into\u0020an\u0020array\u0020with\u0020fixed\u0020structure\u003A\n\u002D\u00204\u0020top\u0020level\u0020keys\u003A\u0020data,\u0020id,\u0020started,\u0020lastUpdate",
            "url": "classes/Collecthor-DataInterfaces-RecordInterface.html#method_asArray"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\StringValueInterface",
            "name": "StringValueInterface",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-StringValueInterface.html"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\StringValueInterface\u003A\u003AgetRawValue\u0028\u0029",
            "name": "getRawValue",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-StringValueInterface.html#method_getRawValue"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\ValueInterface",
            "name": "ValueInterface",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-ValueInterface.html"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\ValueInterface\u003A\u003AgetRawValue\u0028\u0029",
            "name": "getRawValue",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-ValueInterface.html#method_getRawValue"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\ValueOptionInterface",
            "name": "ValueOptionInterface",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-ValueOptionInterface.html"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\ValueOptionInterface\u003A\u003AgetRawValue\u0028\u0029",
            "name": "getRawValue",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-ValueOptionInterface.html#method_getRawValue"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\ValueOptionInterface\u003A\u003AgetDisplayValue\u0028\u0029",
            "name": "getDisplayValue",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-ValueOptionInterface.html#method_getDisplayValue"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\ValueOptionInterface\u003A\u003AgetDisplayValues\u0028\u0029",
            "name": "getDisplayValues",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-ValueOptionInterface.html#method_getDisplayValues"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\ValueOptionInterface\u003A\u003ADEFAULT_LOCALE",
            "name": "DEFAULT_LOCALE",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-ValueOptionInterface.html#constant_DEFAULT_LOCALE"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\ValueSetInterface",
            "name": "ValueSetInterface",
            "summary": "Models\u0020a\u0020value\u0020that\u0020contains\u0020multiple\u0020ValueOptions.",
            "url": "classes/Collecthor-DataInterfaces-ValueSetInterface.html"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\ValueSetInterface\u003A\u003AgetValues\u0028\u0029",
            "name": "getValues",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-ValueSetInterface.html#method_getValues"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\VariableInterface",
            "name": "VariableInterface",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-VariableInterface.html"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\VariableInterface\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-VariableInterface.html#method_getName"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\VariableInterface\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-VariableInterface.html#method_getTitle"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\VariableInterface\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "Extracts\u0020the\u0020variable\u0020value\u0020from\u0020a\u0020record",
            "url": "classes/Collecthor-DataInterfaces-VariableInterface.html#method_getValue"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\VariableInterface\u003A\u003AgetDisplayValue\u0028\u0029",
            "name": "getDisplayValue",
            "summary": "Extract\u0020a\u0020display\u0020value\u0020from\u0020a\u0020record\nIf\u0020a\u0020locale\u0020is\u0020given\u0020the\u0020display\u0020value\u0020should\u0020be\u0020returned\u0020using\u0020the\u0020given\u0020locale.\u0020If\u0020the\u0020locale\u0020is\u0020not\u0020available\na\u0020fallback\u0020MUST\u0020be\u0020used\u0020and\u0020an\u0020exeception\u0020MUST\u0020NOT\u0020be\u0020thrown",
            "url": "classes/Collecthor-DataInterfaces-VariableInterface.html#method_getDisplayValue"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\VariableInterface\u003A\u003AgetMeasure\u0028\u0029",
            "name": "getMeasure",
            "summary": "Return\u0020the\u0020type\u0020of\u0020measure\u0020for\u0020this\u0020variable",
            "url": "classes/Collecthor-DataInterfaces-VariableInterface.html#method_getMeasure"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\VariableSetInterface",
            "name": "VariableSetInterface",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-VariableSetInterface.html"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\VariableSetInterface\u003A\u003AgetVariableNames\u0028\u0029",
            "name": "getVariableNames",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-VariableSetInterface.html#method_getVariableNames"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\VariableSetInterface\u003A\u003AgetVariable\u0028\u0029",
            "name": "getVariable",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-VariableSetInterface.html#method_getVariable"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces\\VariableSetInterface\u003A\u003AgetVariables\u0028\u0029",
            "name": "getVariables",
            "summary": "",
            "url": "classes/Collecthor-DataInterfaces-VariableSetInterface.html#method_getVariables"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Collecthor\\DataInterfaces",
            "name": "DataInterfaces",
            "summary": "",
            "url": "namespaces/collecthor-datainterfaces.html"
        },                {
            "fqsen": "\\Collecthor",
            "name": "Collecthor",
            "summary": "",
            "url": "namespaces/collecthor.html"
        }            ]
);
