name: Continous integration
on: [push, pull_request]
jobs:
  code_checks:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: symplify/easy-coding-standard, psalm, phpstan
      - name: Test code style
        run: ecs
      - name: Static analysis (phpstan)
        run: phpstan
      - name: Create autoloader
        run: composer dumpa
      - name: Static analysis (Psalm)
        run: psalm
  docs:
    name: Create docs
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs:
      - code_checks
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpDocumentor
      - name: Create docs
        run: phpdoc run
      - name: Deploy docs to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
  release:
    name: Automated release
    if: ${{ github.ref == 'refs/heads/master' }}
    needs:
      - code_checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - run: >
          npx
          -p "@semantic-release/commit-analyzer"
          -p "@semantic-release/release-notes-generator"
          -p "@semantic-release/github"
          -p conventional-changelog-conventionalcommits
          -p semantic-release
          -- semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
