name: Continous integration
on: [push, pull_request]
jobs:
  commitlint:
    name: commit-lint
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-commit-lint@v1
        with:
          config: conventional
  cs:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: symplify/easy-coding-standard, phpstan, phpDocumentor
      - name: Test code style
        run: ecs
      - name: Create docs
        run: phpdoc run
      - name: Deploy coverage to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
  release:
    name: Automated release
    needs:
      - cs
      - commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: >
          npx
          -p "@semantic-release/commit-analyzer"
          -p "@semantic-release/release-notes-generator"
          -p "@semantic-release/github"
          -p conventional-changelog-conventionalcommits
          -p semantic-release
          -- semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
